### ISSUE TITLE
Doesn't work on 11.2

### ISSUE THREAD

**Issue by rodyaj** [yurivict/vm-to-tor#1]
Hi. I realise this hasn't received updates in a while, but wondered if it would be simple to fix for FreeBSD 11.2. I tried installing with pkg and including the source to the simple config in rc.conf, but the service reports a failure to start for both vm-to-tor and the included dhcp service, with no further error logs as far as I can see. It seems that the ipfw rules get loaded and /var/log/messages shows the tap device getting initialised, though it is not listed by ifconfig after the failure.

**Comment by yurivict** [comment]
I didn't run vm-to-tor for a while. I will update it.

**Comment by rodyaj** [comment]
Thanks for the quick response. Will look forward to trying it out.

**Comment by yurivict** [comment]
I fixed vm-to-tor and now it works on 11.2. Tor options changed, python paths were wrong. ...

Now you need to update the ports tree and install the port: ```cd /usr/ports/security/vm-to-tor && make install clean```

It works for me with Arch linux VM.

Please let me know if you encounter any problems.

Thanks for using vm-to-tor!

**Comment by rodyaj** [comment]
Excellent. Good catch on needing to add `link0`.

**Comment by yurivict** [comment]
Thanks!
